Footer redesign
immortalv/immortal_home pull request #126
Opened 2022-02-17 20:04 UTC by bohdan-ukr

2022-02-18 07:46 UTC, AndriyTykhan commented on src/pages/home/style.scss
> +  color: red;
Let just use tailwind

2022-02-18 07:46 UTC, AndriyTykhan commented on src/components/footer/footer.js
> +import { Link } from "react-router-dom";
Keep import order correct

2022-03-16 09:20 UTC, AndriyTykhan commented on src/components/footer/footer.js
> +            phoneNumberText="+380730297300"
Please move this props to constants

2022-03-16 09:20 UTC, AndriyTykhan commented on src/components/footer/footer.js
>  import React from "react";
Keep import order!

And person who left comment, resolves it

2022-03-16 09:20 UTC, AndriyTykhan requested changes
Fix comments

2022-03-16 17:47 UTC, bohdan-ukr commented on src/components/footer/footer.js
>  import React from "react";
Sorry, Its my configuration in vs code setting and every time when im saving anything it sometimes change order. I will resolve it

2022-03-17 11:44 UTC, AndriyTykhan approved these changes

2022-03-17 11:45 UTC, merged