added: code style convention and updated dependencies
immortalv/immortal_home pull request #143
Opened 2022-04-20 06:45 UTC by andriiwp3

- React was updated to v18
- all dependencies updated
- eslint and prettier added and configured
- the whole project was linted and formatted
- pre-commit hooks added and configured
- added props typing for all components
- .gitignore file updated
- the project documentation README.md file has been improved

2022-04-20 08:21 UTC, AndriyTykhan commented on .prettierrc.js
> +	printWidth: 100,
Let's make it 120 or 160

2022-04-20 08:21 UTC, AndriyTykhan commented on .eslintrc.js
> +				printWidth: 100,
Let's make it 160

2022-04-20 08:25 UTC, AndriyTykhan commented on src/App.js
> +	const { user } = useAuth0();
Well, it really looks too big. Let's return spaces how they were before

2022-04-20 08:28 UTC, AndriyTykhan requested changes
Please return old space and quotes configuration

2022-04-20 09:07 UTC, andriiwp3 commented on .eslintrc.js
> +				printWidth: 100,
@AndriyTykhan May be better 120?

2022-04-20 11:30 UTC, AndriyTykhan commented on .eslintrc.js
> +				printWidth: 100,
Okay, lets make it 120

2022-04-21 17:49 UTC, AndriyTykhan approved these changes

2022-04-21 18:18 UTC, merged