Maks/IMD-2 Fix problems with pagination feature
immortalv/immortal_home pull request #171
Opened 2023-05-04 11:33 UTC by KovalenkoMaks

## Description
Change logic of pagination works. Now is work correct

## JIRA ticket
- [IMD-{TICKET-NUMBER}](https://immortalv.atlassian.net/browse/IMD-2)

2023-05-04 12:50 UTC, andriiwp3 requested changes

2023-05-04 12:50 UTC, andriiwp3 commented on src/pages/profiles/profiles.page.js
> +      setPage(parseInt(storedPage));
I guess `parseInt()` accepts 2 arguments

2023-05-04 12:50 UTC, andriiwp3 commented on src/pages/profiles/profiles.page.js
> +    sessionStorage.setItem('currentPage', value);
Please expose it to constant

2023-05-04 13:09 UTC, KovalenkoMaks commented on src/pages/profiles/profiles.page.js
> +  const [page, setPage] = useState(() => parseInt(sessionStorage.getItem('currentPage')) || 1);
because we have to save number of page between refreshing of page. I think it is not a bad idea.

2023-05-04 14:10 UTC, KovalenkoMaks commented on src/pages/profiles/profiles.page.js
> +      setPage(parseInt(storedPage));
yes, but if we enter only 1 argument, default value of the second argument will be 10, as we need. or I can do it with + instead of parseInt()

2023-05-04 14:14 UTC, KovalenkoMaks commented on src/pages/profiles/profiles.page.js
> +    sessionStorage.setItem('currentPage', value);
done

2023-05-04 18:23 UTC, KovalenkoMaks commented
@andriiwp3 I change all logics of pagination. Now I used useLocation and useSearchParams. I think it will be better

2023-05-08 14:49 UTC, KovalenkoMaks commented
@andriiwp3 I resolved all  conversations, please give me new review.

2023-05-09 06:29 UTC, andriiwp3 commented on src/pages/profiles/profiles.page.js
> +  const [page, setPage] = useState(() => parseInt(sessionStorage.getItem('currentPage')) || 1);
I think the use of parameters is better and more user-centric, so please change it

2023-05-09 06:29 UTC, andriiwp3 commented on src/pages/profiles/profiles.page.js
> +      setPage(parseInt(storedPage));
eslint argues if you use parseInt with 1 argument and i guess it's better to use unaric plus

2023-05-09 09:41 UTC, KovalenkoMaks commented on src/pages/profiles/profiles.page.js
> +  const [page, setPage] = useState(() => parseInt(sessionStorage.getItem('currentPage')) || 1);
I have already done it. Please check  [Files changed](https://github.com/immortalv/immortal_home/pull/171/files)

2023-05-09 09:43 UTC, KovalenkoMaks commented on src/pages/profiles/profiles.page.js
> +      setPage(parseInt(storedPage));
yes, you are right

2023-05-12 09:56 UTC, andriiwp3 requested changes

2023-05-12 09:56 UTC, andriiwp3 commented on src/pages/profiles/profiles.page.js
> +  const [page, setPage] = useState(+location.search.slice(-1) || 1);
What if the page number is xx or more? `slice(-1)` won't work

2023-05-12 09:56 UTC, andriiwp3 commented on src/pages/profiles/profiles.page.js
> +  const [, setSearchParams] = useSearchParams({});
Why did you skip the first parameter?

2023-05-12 10:56 UTC, KovalenkoMaks commented on src/pages/profiles/profiles.page.js
> +  const [, setSearchParams] = useSearchParams({});
Because I don`t use it.

2023-05-12 12:39 UTC, andriiwp3 approved these changes

2023-05-12 12:40 UTC, IgorMysak1 approved these changes

2023-05-12 12:40 UTC, merged