Maks/IMD-6 first and last names validation
immortalv/immortal_home pull request #173
Opened 2023-05-04 12:13 UTC by KovalenkoMaks

## Description
Add validation for first and last names, which have to be not less then 2 symbols (Latin and Cyrillic letters) and/or a dash

## JIRA ticket
- [IMD-6](https://immortalv.atlassian.net/browse/IMD-6)

## Related PRs (Optional)
- https://github.com/immortalv/immortal_server/pull/23

2023-05-08 09:32 UTC, andriiwp3 commented on src/components/profiles/add-profile/steps/main-info.component.js
> +      return /^[a-zA-Zа-яА-ЯіІїЇєЄ']{2,}(-[a-zA-Zа-яА-ЯіІїЇєЄ']+)*$/.test(name);
If you want to show that we expect only letters, we can use `/w`

2023-05-08 15:27 UTC, KovalenkoMaks commented on src/components/profiles/add-profile/steps/main-info.component.js
> +      return /^[a-zA-Zа-яА-ЯіІїЇєЄ']{2,}(-[a-zA-Zа-яА-ЯіІїЇєЄ']+)*$/.test(name);
fixed it

2023-05-08 18:57 UTC, andriiwp3 requested changes

2023-05-08 18:57 UTC, andriiwp3 commented on src/components/profiles/add-profile/steps/main-info.component.js
> +      return /[\wа-яА-ЯёЁіІїЇєЄ]{2,}(-[\wа-яА-ЯёЁіІїЇєЄ]+)*$/.test(name);
if we use `\w' => we don't need the `a-яА-Я...` part and please don't mark conversations as resolved

2023-05-12 13:10 UTC, andriiwp3 commented on src/components/profiles/add-profile/steps/main-info.component.js
> +      return /[\wа-яА-ЯёЁіІїЇєЄ]{2,}(-[\wа-яА-ЯёЁіІїЇєЄ]+)*$/.test(name);
it was discussed during the meeting and we agreed to leave it as it is

2023-05-12 13:10 UTC, merged