Maks/IMD-5 Change route for profiles page
immortalv/immortal_home pull request #177
Opened 2023-05-08 08:11 UTC by KovalenkoMaks

## Description
Change route for profiles page from lazy to simple import. 

## JIRA ticket
- [IMD-5](https://immortalv.atlassian.net/browse/IMD-5)

2023-05-08 18:51 UTC, andriiwp3 requested changes

2023-05-08 18:51 UTC, andriiwp3 commented on src/router/routes.js
> +import { ProfilesPage } from 'pages/profiles';
I think it should be possible to save lazy loading, we don't want another page to load on the main page

2023-05-10 19:26 UTC, KovalenkoMaks commented on src/router/routes.js
> +import { ProfilesPage } from 'pages/profiles';
fixed it

2023-05-15 13:49 UTC, andriiwp3 approved these changes

2023-05-15 13:50 UTC, merged