Maks/IMD-11 Add footer styles
immortalv/immortal_home pull request #179
Opened 2023-05-09 12:28 UTC by KovalenkoMaks

Change footer styles from 480 to 766px as mobile

2023-05-12 10:09 UTC, andriiwp3 commented
Could you please attach screenshots?

2023-05-12 11:21 UTC, KovalenkoMaks commented
![481](https://github.com/immortalv/immortal_home/assets/116664804/601631f4-2e98-46d4-8c1c-3bd791a4f95b)
![766](https://github.com/immortalv/immortal_home/assets/116664804/82795562-c168-444e-afa0-a7bc245eaca9)

2023-05-12 12:07 UTC, IgorMysak1 requested changes
Please improve responsiveness as it seems to be quite poor now
Check [this message](https://immortal-eyw9559.slack.com/archives/C057JATPHRA/p1683893379158329)

2023-05-15 13:51 UTC, andriiwp3 approved these changes

2023-05-15 13:51 UTC, merged